version: '3.8'
services:
    php-laravel:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mysql
            - redis
        ports:
            - 80:80
        networks:
            - app
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - app
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - app
networks:
    app:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
